#coding: utf-8
import pandas as pd
rs = pd.read_csv("car_complain.csv")
rs = rs.drop('problem',1).join(rs.problem.str.get_dummies(','))
df = rs.groupby('brand')['id'].agg(['count']).sort_values(by="count",ascending=False)
print("品牌投诉总数：\n",df)
df1 = rs.groupby(['brand','car_model'])['id'].agg(['count'])
df1 = df1.sort_values('count',ascending = False)
print("车型投诉总数：\n",df1)
df2 = rs.groupby(['brand']).car_model.nunique()
df3 = pd.merge(df,df2,on="brand")
df3["mean"] = df3.apply(lambda x:x[0]/x[1],axis=1)
df3 = df3.sort_values(by="mean",ascending=False)
print("品牌平均车型投诉数：\n",df3)
#品牌平均车型平均问题数
rs["totalP"] = rs.iloc[:,8:].sum(axis=1)
df4 = rs.groupby(['brand'])['totalP'].agg(['sum'])
df5 = pd.merge(df2,df4,on='brand')
df5['mean'] = df5.apply(lambda x:x[1]/x[0],axis=1)
df5 = df5.sort_values(by='mean',ascending=False)
print("品牌平均车型平均问题数：\n",df5)
